spring:
  rabbitmq:
    host: 10.250.7.21
    port: 30730
    username: guest
    password: guest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dbtaobao.com:3306/taobao71_remote
    username: taobao71
    password: taobao71
    max-idle: 5
    max-wait: 1000
    min-idle: 5
    initial-size: 5